### PR TITLE
Sponsor List Page Functionality

### LINKED ISSUE #69: Sponsor List Page Functionality
**Description**
Create the sponsor list page and include the sponsor cards as well as the update functionality. Populate cards with test data. Associate updates with pending reimbursement requests of the organization

**Acceptance Criteria**

Steps:
- render sponsor card components on sponsor page
- create test data for sponsor cards
- develop update functionality

### PR DESCRIPTION
**Pull request by peterchinh**
## Developer: Peter Chinh

Closes #69 

### Pull Request Summary

Implemented rendering of sponsor card components to sponsor page. Created test data for it. Implemented update functionality with the view toggles to show all sponsors and updated sponsors.

### Modifications

/src/app/sponsors/page.tsx - Added functions, test data, component rendering, and react hooks.

### Testing Considerations

Went on the sponsors page to see if sponsors card all rendered. Clicked the toggle to see if the all sponsors cards were displayed and if only 3 updated sponsors card were displayed.

### Pull Request Checklist

- [x] Code is neat, readable, and works
- [x] Comments are appropriate
- [x] The commit messages follows our [guidelines](https://h4i.notion.site/Conventional-Commits-593452ad1179489399ad3bd696ef772a)
- [x] The developer name is specified
- [x] The summary is completed
- [ ] Assign reviewers

### Screenshots/Screencast
image
image

### CODE REVIEW

**Review by s-iloo — CHANGES_REQUESTED** [review]
Hey Peter, everything looks great apart from one minor thing! For the view updates toggle, could you render the sponsor cards so that they're spaced like in the figma?

**Comment by peterchinh** [comment]
image

**Review by s-iloo — CHANGES_REQUESTED** [review]
Could you make the spacing of the cards a tiny bit closer so that the fifth card fits on the same row?

**Review by s-iloo — APPROVED** [review]
Looks good to me!

**Pull request merged**
