### PR TITLE
Ktaschek miscellaneous

### PR DESCRIPTION
**Pull request by ryanhu021**
## Developer: {Full Name}

Closes #{ISSUE NUMBER HERE}

### Pull Request Summary

{Describe the purpose of your pull request}

### Modifications

{list out the files created/modified and a brief description of what was changed}

### Testing Considerations

{list out what you have tested and what the reviewer should verify}

### Pull Request Checklist

- [ ] Code is neat, readable, and works
- [ ] Comments are appropriate
- [ ] The commit messages follows our [guidelines](https://h4i.notion.site/Conventional-Commits-593452ad1179489399ad3bd696ef772a)
- [ ] The developer name is specified
- [ ] The summary is completed
- [ ] Assign reviewers

### Screenshots/Screencast

{put screenshots of your change, or even better a screencast displaying the functionality}

### CODE REVIEW

**Review by s-iloo — CHANGES_REQUESTED** [review]
Hey Kyle, can you make it so the x isn't overlapping the text box?

image

**Comment by ryanhu021** [comment]
oh shoot thanks for catching that

**Comment by ktaschek** [comment]
I can't commit to here anymore so ill make a new PR, but I also found a thread saying dialog pop ups have issues with overflow since you can't scroll on them if the window is too small. Would it be appropriate to also add "overflow-y-scroll max-h-screen" to the dialogcontent component?

**Comment by ryanhu021** [comment]
yes i think that would be good, just make sure it doesn't scroll when the screen is big enough

**Comment by ktaschek** [comment]
Nevermind I realized its kind of non issue for us because the dialogue pop ups are pretty small and I'm too lazy to remove the scroll bar which appears even if it fits

**Review by s-iloo — APPROVED** [review]
LGTM

**Pull request merged**
