### PR TITLE
style: center spinner

### LINKED ISSUE #140: Center loading spinners
**Description**
Center all the loading spinners to the center of the page (they are currently top right).

**Acceptance Criteria**

Steps:

- style the loading spinners to render at the center of the page

### PR DESCRIPTION
**Pull request by vilinh**
## Developer: Vi-Linh Vu

Closes #140 

### Pull Request Summary

Center spinner.

### Modifications

- `src/components/centered-spinner.tsx`: Centered spinner by making component take up full width/height.

### Testing Considerations

Tested locally. Kind of doesn't look centered vertically bc the page by default takes up more than 100% browser height.

### Pull Request Checklist

- [X] Code is neat, readable, and works
- [X] Comments are appropriate
- [X] The commit messages follows our [guidelines](https://h4i.notion.site/Conventional-Commits-593452ad1179489399ad3bd696ef772a)
- [X] The developer name is specified
- [X] The summary is completed
- [X] Assign reviewers

### Screenshots/Screencast

https://github.com/hack4impact-calpoly/ecologistics-portal/assets/81380688/d977fc72-23f6-4181-a389-a8922c5412a1

### CODE REVIEW

**Review by ryanhu021 — CHANGES_REQUESTED** [review]
instead of stretching the spinner component to the size of the screen, could you have it fill the size of the parent component instead?

**Comment by vilinh** [comment]
Yes, but that would require that the parent component has a set height and width. Or else it's just simply wrapping the child. So do you want me to modify the parents that are using the `<CenteredSpinner />` too?

**Comment by ryanhu021** [comment]
i don't think you need to modify the parent components, try doing `m-auto` instead of `w-screen h-screen`. since this is the component-centered spinner, we don't need it to stretch the parent component.

**Comment by vilinh** [comment]
I tried it and it doesn't work. If I don't modify the parent component, the spinner will only take up its own width and height.

It's being used like this in various pages:
`  if (!isLoaded) {
    return (
      <div>
        <CenteredSpinner />
      </div>
    );
  }`

So if the parent component doesn't have a width and height, making the component take up 100% of the width/height of its parent component doesn't do anything. Likewise, I think that's why doing `m-auto` doesn't work. The parent right now is just simply a `div` with no styling so it's just wrapping it.

image

This is how it looks like when I just set `m-auto`, I made the background color red to see the width and height of the component.

**Comment by ryanhu021** [comment]
oh I see, could you modify the parent components then to just render the component by itself?

**Comment by vilinh** [comment]
I don't know if this is what you mean, but now I just made the parent components full width/height of the screen and `<CenteredSpinner />` just 100% width/height of parent. I can change it still if you meant something else.

**Comment by ryanhu021** [comment]
sorry for the confusion, i meant just do `return <CenteredSpinner />` in the parent components instead of `<div><CenteredSpinner /></div>`. we want `CenteredSpinner` to just be in the middle of whatever component is it's parent; for example, a `CenteredSpinner` under a card will just be in the middle of the card, not the entire screen. `FullScreenSpinner` is the component that is always in the middle of the entire screen.

**Review by ryanhu021 — APPROVED** [review]
perfect! thanks for being so on top of this!

**Pull request merged**
