### PR TITLE
Taran Singh - Issue 184

### LINKED ISSUE #184: Fix Sizing of Status Dropdown in Sponsor Reimbursements Homepage
**Description**
Style the status drop down according to the figma (it is way too long right now). 
Note: We don't have the preferred payment and organization dropdowns in this table. 

Current:
image

Figma:
image

### PR DESCRIPTION
**Pull request by tarannssingh**
## Developer: Taran Singh

Closes #184 

### Pull Request Summary

I edited the styling of the request page. The top drop down section looks cleaner

### Modifications

`/src/components/sponsored-org-table/data-table.tsx`

### Testing Considerations

I visually tested the styling.

### Pull Request Checklist

- [x] Code is neat, readable, and works
- [x] Comments are appropriate
- [x] The commit messages follows our [guidelines](https://h4i.notion.site/Conventional-Commits-593452ad1179489399ad3bd696ef772a)
- [x] The developer name is specified
- [x] The summary is completed
- [x] Assign reviewers

### Screenshots/Screencast

{put screenshots of your change, or even better a screencast displaying the functionality}
Screenshot 2024-05-19 at 2 52 20 PM

### CODE REVIEW

**Comment by s-iloo** [comment]
Might have to try merging again Taran, I just pushed some changes to that page to develop right before you made this pr

**Comment by tarannssingh** [comment]
Hi Ian, I remerged my branch.

**Comment by s-iloo** [comment]
> Hi Ian, I remerged my branch.

Hey Taran, looks like it's still not building correctly, try building again and seeing what errors occur. 

image

**Comment by ryanhu021** [comment]
looks like it doesn't allow JSX in the placeholder, try just putting a plain string there

**Review by ryanhu021 — APPROVED** [review]

**Pull request merged**
